export const prayerActivities = [
  {
    name: "Shalat Tahajud",
    note: "setelah isya` - sebelum subuh (setelah tidur terlebih dahulu)",
    initialTime: "02.00",
    isNextPage: false,
  },
  {
    name: "Shalat Subuh",
    note: "lebih tepatnya lihat jadwal",
    initialTime: "04.00",
    isNextPage: true,
    page: "/",
    prayer: "Subuh",
  },
  {
    name: "Membaca Al-Qur`an",
    note: "setelah shalat subuh",
    initialTime: "05.00",
    isNextPage: false,
  },
  {
    name: "Dzikir Pagi",
    note: "setelah shalat subuh",
    initialTime: "05.15",
    isNextPage: true,
    page: "/dzikir-pagi",
  },
  {
    name: "Shalat Dhuha",
    note: "waktu dhuha",
    initialTime: "07.00",
    isNextPage: false,
  },
  {
    name: "Shalat Dzuhur",
    note: "lebih tepatnya lihat jadwal",
    initialTime: "12.00",
    isNextPage: true,
    page: "/",
    prayer: "Dzuhur",
  },
  {
    name: "Shalat Ashar",
    note: "lebih tepatnya lihat jadwal",
    initialTime: "15.00",
    isNextPage: true,
    page: "/",
    prayer: "Ashar",
  },
  {
    name: "Dzikir Petang",
    note: "setelah shalat ashar",
    initialTime: "15.30",
    isNextPage: true,
    page: "/dzikir-petang",
  },
  {
    name: "Shalat Maghrib",
    note: "lebih tepatnya lihat jadwal",
    initialTime: "18.00",
    isNextPage: true,
    page: "/",
    prayer: "Maghrib",
  },
  {
    name: "Membaca Al-Qur`an",
    note: "setelah shalat maghrib",
    initialTime: "18.30",
    isNextPage: false,
  },
  {
    name: "Shalat Isya`",
    note: "lebih tepatnya lihat jadwal",
    initialTime: "19.00",
    isNextPage: true,
    page: "/",
    prayer: "Isya",
  },
];
